import { FieldValues } from 'react-hook-form';
import { InputState } from '../components/FormInput/TextInput.types';
declare const useIndyForm: <T extends FieldValues>() => {
    methods: import("react-hook-form").UseFormReturn<T, any, undefined>;
    registerWithState: (id: keyof T) => {
        id: keyof T;
        state: InputState;
        message: string | ("message" extends infer T_1 ? T_1 extends "message" ? T_1 extends keyof import("react-hook-form").FieldError & keyof import("react-hook-form").DeepRequired<T>[string] ? [import("react-hook-form").FieldError[T_1], import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[string]>[T_1]] extends [object, object] ? import("react-hook-form").Merge<import("react-hook-form").FieldError[T_1], import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[string]>[T_1]> : import("react-hook-form").FieldError[T_1] | import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[string]>[T_1] : T_1 extends keyof import("react-hook-form").FieldError ? import("react-hook-form").FieldError[T_1] : T_1 extends keyof import("react-hook-form").DeepRequired<T>[string] ? import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[string]>[T_1] : never : never : never) | ("message" extends infer T_2 ? T_2 extends "message" ? T_2 extends keyof import("react-hook-form").FieldError & keyof import("react-hook-form").DeepRequired<T>[number] ? [import("react-hook-form").FieldError[T_2], import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[number]>[T_2]] extends [object, object] ? import("react-hook-form").Merge<import("react-hook-form").FieldError[T_2], import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[number]>[T_2]> : import("react-hook-form").FieldError[T_2] | import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[number]>[T_2] : T_2 extends keyof import("react-hook-form").FieldError ? import("react-hook-form").FieldError[T_2] : T_2 extends keyof import("react-hook-form").DeepRequired<T>[number] ? import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[number]>[T_2] : never : never : never) | ("message" extends infer T_3 ? T_3 extends "message" ? T_3 extends keyof import("react-hook-form").FieldError & keyof import("react-hook-form").DeepRequired<T>[symbol] ? [import("react-hook-form").FieldError[T_3], import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[symbol]>[T_3]] extends [object, object] ? import("react-hook-form").Merge<import("react-hook-form").FieldError[T_3], import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[symbol]>[T_3]> : import("react-hook-form").FieldError[T_3] | import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[symbol]>[T_3] : T_3 extends keyof import("react-hook-form").FieldError ? import("react-hook-form").FieldError[T_3] : T_3 extends keyof import("react-hook-form").DeepRequired<T>[symbol] ? import("react-hook-form").FieldErrorsImpl<import("react-hook-form").DeepRequired<T>[symbol]>[T_3] : never : never : never) | undefined;
    };
};
export default useIndyForm;
