/// <reference types="react" />
export declare const TagLine: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("styled-components/dist/types").FastOmit<import("styled-components/dist/types").Substitute<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, Omit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, "ref"> & {
    ref?: ((instance: HTMLSpanElement | null) => void) | import("react").RefObject<HTMLSpanElement> | null | undefined;
}>, never>, never>>;
export declare const Title: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>, never>>;
export declare const Wrapper: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<Omit<import("../StepCard/StepCard.types").default, "ref"> & import("react").RefAttributes<HTMLDivElement>, never>> & Omit<import("react").ForwardRefExoticComponent<Omit<import("../StepCard/StepCard.types").default, "ref"> & import("react").RefAttributes<HTMLDivElement>>, keyof import("react").Component<any, {}, any>>;
export declare const InnerWrapper: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const StepAndTitleWrapper: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const Description: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, never>>;
export declare const GoBackToPreviousStep: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").Substitute<import("styled-components/dist/types").Substitute<import("styled-components/dist/types").Substitute<(Omit<import("../Button/Button.types").ButtonType, "ref"> | Omit<import("../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>, (Omit<import("../Button/Button.types").ButtonType, "ref"> | Omit<import("../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>>, import("styled-components/dist/types").BaseObject>, import("styled-components/dist/types").BaseObject>> & Omit<import("react").ForwardRefExoticComponent<(Omit<import("../Button/Button.types").ButtonType, "ref"> | Omit<import("../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>>, keyof import("react").Component<any, {}, any>>;
