/// <reference types="react" />
export declare const Wrapper: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const Cards: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const Card: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const Image: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const Text: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const TextContainer: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const Buttons: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>>;
export declare const CompareButton: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").Substitute<(Omit<import("../../Button/Button.types").ButtonType, "ref"> | Omit<import("../../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>, import("styled-components/dist/types").BaseObject>> & Omit<import("react").ForwardRefExoticComponent<(Omit<import("../../Button/Button.types").ButtonType, "ref"> | Omit<import("../../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>>, keyof import("react").Component<any, {}, any>>;
export declare const ClearButton: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").Substitute<import("styled-components/dist/types").Substitute<import("styled-components/dist/types").Substitute<(Omit<import("../../Button/Button.types").ButtonType, "ref"> | Omit<import("../../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>, (Omit<import("../../Button/Button.types").ButtonType, "ref"> | Omit<import("../../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>>, import("styled-components/dist/types").BaseObject>, import("styled-components/dist/types").BaseObject>> & Omit<import("react").ForwardRefExoticComponent<(Omit<import("../../Button/Button.types").ButtonType, "ref"> | Omit<import("../../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>>, keyof import("react").Component<any, {}, any>>;
export declare const Status: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLElement>, HTMLElement>, never>>;
