/// <reference types="react" />
export declare const Wrapper: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("../SubscriptionPricingCard/Base/SubscriptionPricingCard.types").default, never>> & Omit<import("react").FC<import("../SubscriptionPricingCard/Base/SubscriptionPricingCard.types").default>, keyof import("react").Component<any, {}, any>>;
export declare const SubPackageType: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>, never>>;
export declare const SubPackageLength: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, never>>;
export declare const NewPrice: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLElement>, HTMLElement>, never>>;
export declare const OldPrice: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, never>>;
export declare const TakeThisOfferButton: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").Substitute<(Omit<Omit<import("../Button/Button.types").ButtonType, "ref"> & import("react").RefAttributes<HTMLButtonElement>, "ref"> & {
    ref?: ((instance: HTMLButtonElement | null) => void) | import("react").RefObject<HTMLButtonElement> | null | undefined;
}) | (Omit<Omit<import("../Button/Button.types").LinkType, "ref"> & import("react").RefAttributes<HTMLButtonElement>, "ref"> & {
    ref?: ((instance: HTMLButtonElement | null) => void) | import("react").RefObject<HTMLButtonElement> | null | undefined;
}), import("styled-components/dist/types").BaseObject>> & Omit<import("react").ForwardRefExoticComponent<(Omit<import("../Button/Button.types").ButtonType, "ref"> | Omit<import("../Button/Button.types").LinkType, "ref">) & import("react").RefAttributes<HTMLButtonElement>>, keyof import("react").Component<any, {}, any>>;
export declare const Terms: import("styled-components").IStyledComponent<"web", import("styled-components/dist/types").FastOmit<import("react").DetailedHTMLProps<import("react").HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, never>>;
